const Menu = [
  {
    _id: 1,
    image: "images/Zinger burger.png",
    name: "Zinger Burger",
    category: "burger",
    availability: true,
    price: 100,
  },
  {
    _id: 2,
    image: "images/Hot n cripsy burger.png",
    name: "Hot n Crispy Burger",
    category: "burger",
    availability: true,
    price: 110,
  },
  {
    _id: 3,
    image: "images/Cheese Burger.png",
    name: "Cheese Burger",
    category: "burger",
    availability: true,
    price: 150,
  },
  {
    _id: 4,
    image: "images/Mini McRoyale.png",
    name: "Mini McRoyale",
    category: "burger",
    availability: true,
    price: 340,
  },
  {
    _id: 5,
    image: "images/Chicken Burger with cheese.png",
    name: "Chicken Burger with Cheese",
    category: "burger",
    availability: true,
    price: 30,
  },
  {
    _id: 6,
    image: "images/chicken burger.png",
    name: "Grand Chicken Spicy",
    category: "burger",
    availability: true,
    price: 110,
  },
  {
    _id: 7,
    image: "images/Chicken Corn Soup.png",
    name: "Chicken Corn Soup",
    category: "chinese",
    availability: true,
    price: 110,
  },
  {
    _id: 8,
    image: "images/Chicken Wonton Soup.png",
    name: "Chicken Wonton Soup",
    category: "chinese",
    availability: true,
    price: 200,
  },
  {
    _id: 9,
    image: "images/2 Pcs Chicken With Egg Fried Rice.png",
    name: "Chicken With Egg Fried Rice",
    category: "chinese",
    availability: true,
    price: 199,
  },
  {
    _id: 10,
    image: "images/Veg cheese pizza.jpg",
    name: "Veg Cheese Pizza",
    category: "pizza",
    availability: true,
    price: 100,
  },
  {
    _id: 11,
    image: "images/Veg Pizza.png",
    name: " Double Cheese Pizza",
    category: "pizza",
    availability: true,
    price: 119,
  },
  {
    _id: 12,
    image: "images/Coca cola.png",
    name: "Coca cola",
    category: "softdrink",
    availability: true,
    price: 110,
  },
  {
    _id: 13,
    image: "images/Bavaria Non-Alcoholic Malt Drink Peach Bottle.png",
    name: "Bavaria Non-Alcoholic Malt Drink Peach Bottle",
    category: "softdrink",
    availability: true,
    price: 90,
  },
  {
    _id: 14,
    image: "images/sprite.png",
    name: "sprite",
    category: "softdrink",
    availability: true,
    price: 99,
  },
  {
    _id: 15,
    image: "images/Schweppes Premium Mixer Soda Water.png",
    name: "Schweppes Premium Mixer Soda Water",
    category: "softdrink",
    availability: true,
    price: 140,
  },
  {
    _id: 16,
    image: "images/Mountain Dew Soft Drink 155ml.png",
    name: "Mountain Dew Soft Drink 155ml",
    category: "softdrink",
    availability: true,
    price: 140,
  },
  {
    _id: 17,
    image: "images/vanilla.png",
    name: "vanilla",
    category: "ice-cream",
    availability: true,
    price: 290,
  },
  {
    _id: 18,
    image: "images/Strawberry.png",
    name: "Strawberry",
    category: "ice-cream",
    availability: false,
    price: 290,
  },
  {
    _id: 20,
    image: "images/oreo pastry.png",
    name: "Oreo pastry",
    category: "pastry",
    availability: true,
    price: 290,
  },
];

const order = [
  {
    _id: 9,
    image: "images/2 Pcs Chicken With Egg Fried Rice.png",
    name: "Chicken With Egg Fried Rice",
    category: "chinese",
    qty: 1,
    note: "",
    price: 199,
  },
  {
    _id: 20,
    image: "images/oreo pastry.png",
    name: "Oreo pastry",
    category: "pastry",
    qty: 1,
    note: "",
    price: 290,
  },
  {
    _id: 14,
    image: "images/sprite.png",
    name: "sprite",
    category: "softdrink",
    qty: 1,
    note: "",
    price: 99,
  },
];

const Orders = [
  {
    _id: 1,
    items: order,
    customer_Id: 20,
    customerName: "Christopher Nolan",
    discount: 5,
    totalAmount: 1190,
    paymentStatus: "Completed",
    orderStatus: "Delivered",
    tableNo: 4,
  },
  {
    _id: 2,
    items: order,
    customer_Id: 21,
    customerName: "Jane Foster",
    discount: 5,
    totalAmount: 110,
    paymentStatus: "Completed",
    orderStatus: "Preparing",
    tableNo: 4,
  },
  {
    _id: 3,
    items: order,
    customer_Id: 20,
    customerName: "Thor Odinson",
    discount: 5,
    totalAmount: 1190,
    paymentStatus: "Pending",
    orderStatus: "Preparing",
    tableNo: 4,
  },
];

const Tables = [
  { _id: 1, status: "Booked", capacity: 5, order_Id: 9 },
  { _id: 2, status: "Booked", capacity: 6, order_Id: 20 },
  { _id: 3, status: "Vacant", capacity: 5, order_Id: 9 },
  { _id: 4, status: "Booked", capacity: 4, order_Id: 14 },
  { _id: 5, status: "Vacant", capacity: 5, order_Id: 9 },
];

export { order, Menu, Orders, Tables };
